import { useState } from 'react';
import { usePrediction } from '../../hooks/use-ml';
import { formatCurrency } from '../../lib/format';
import LoadingSpinner from '../common/LoadingSpinner';

interface ExploreStepProps {
  onNext: (symbol: string) => void;
}

export default function ExploreStep({ onNext }: ExploreStepProps) {
  const [symbol, setSymbol] = useState('AAPL');
  const [searchSymbol, setSearchSymbol] = useState('AAPL');
  const { data, isLoading, error } = usePrediction(searchSymbol);

  function handleSearch(e: React.FormEvent) {
    e.preventDefault();
    setSearchSymbol(symbol.toUpperCase());
  }

  return (
    <div className="animate-fade-in text-center">
      <h2 className="text-2xl font-bold text-gray-900">Explore AI Predictions</h2>
      <p className="mt-2 text-sm text-gray-600">
        See how our AI analyzes stocks. Try searching for any symbol.
      </p>

      <form onSubmit={handleSearch} className="mx-auto mt-6 flex max-w-xs gap-2">
        <input
          value={symbol}
          onChange={(e) => setSymbol(e.target.value.toUpperCase())}
          placeholder="Symbol (e.g. AAPL)"
          className="block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 focus:outline-none"
        />
        <button
          type="submit"
          className="shrink-0 rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700"
        >
          Search
        </button>
      </form>

      <div className="mx-auto mt-6 max-w-sm">
        {isLoading && <LoadingSpinner className="py-8" />}
        {error && (
          <p className="py-4 text-sm text-red-600">Could not load prediction for {searchSymbol}.</p>
        )}
        {data && !isLoading && (
          <div className="rounded-lg bg-gray-50 p-6 text-left">
            <div className="text-center text-lg font-bold text-gray-900">{data.symbol}</div>
            <div className="mt-4 grid grid-cols-2 gap-4 text-sm">
              <div>
                <div className="text-gray-500">Direction</div>
                <div className={`font-semibold ${data.predicted_direction === 'UP' ? 'text-green-600' : 'text-red-600'}`}>
                  {data.predicted_direction}
                </div>
              </div>
              <div>
                <div className="text-gray-500">Confidence</div>
                <div className="font-semibold text-gray-900">{(data.confidence * 100).toFixed(0)}%</div>
              </div>
              <div>
                <div className="text-gray-500">Current Price</div>
                <div className="font-semibold text-gray-900">{formatCurrency(data.current_price)}</div>
              </div>
              <div>
                <div className="text-gray-500">Predicted Price</div>
                <div className="font-semibold text-gray-900">{formatCurrency(data.predicted_price)}</div>
              </div>
            </div>
          </div>
        )}
      </div>

      <div className="mt-4 rounded-lg bg-indigo-50 p-3">
        <p className="text-xs text-indigo-700">
          Predictions are generated by ML models analyzing market data, sentiment, and technical indicators.
          Always do your own research before trading.
        </p>
      </div>

      <button
        onClick={() => onNext(searchSymbol)}
        className="mt-8 rounded-md bg-indigo-600 px-8 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"
      >
        Continue
      </button>
    </div>
  );
}
